session_name: microviz
start_directory: ./ # load session relative to config location (project root).
before_script: pnpm install
windows:
- window_name: main
  layout: main-horizontal
  focus: true
  options:
    main-pane-height: 35
  start_directory: ./
  panes:
  - focus: true
  - pane
  - pane
  - pane
- window_name: demo
  layout: main-horizontal
  options:
    main-pane-height: 35
  start_directory: ./packages/demo
  panes:
  - focus: true
  - pane
  - pane
  - pane
